#+hugo_base_dir: ../
#+author: Amir M. Taati

* On Existential Loneliness 
:PROPERTIES:
:EXPORT_FILE_NAME: existential-loneliness
:END:

Loneliness is one of those situations which we all have experienced to a certain degree in different points of our lives. It can be claimed that
it is one of the most disturbing and emotionally painful experiences which cannot be described by words precisely. Those who feel lonely on a regular basis
may wonder: Do other people feel lonely as I do?

One of the most common ways in which one finds oneself lonely is when one is alone. In this case you don't have anyone physically around you to
make any kind of contact with. But there exists a much more painful kind of loneliness which I call emotional loneliness. When you're emotionally lonely
it is not that you don't have anyone around you, but rather the people around you do not wish to listen to you. Or maybe your ideas are
simply too vulgar and socially inappropriate that no one wants to listen. In this case you find yourself deeply lonely and disconnected from the outside world.
Having sufficient amount of time, as a result of very little or no human contact at all, you may ask yourself: Is everyone lonely?

People have different experiences of loneliness depending on their situation. Having a supportive family and good friends can certainly help you
feel less lonely and simply much more alive and content. But even in a such an idealistic state you may feel a deep feeling of void and emptiness inside.
Is there anyway out?

Even in a situation where we have our beloved ones around us who are ready to listen to us, we are still stuck within our head. Being listened to
can dramatically decrease the degree to which you feel lonely, but cannot save you from yourself. No matter what, you are lonely deep down inside and
no one can help you. Every individual is isolated to a degree in their head and being surrounded by eight billion other conscious human beings makes
no difference at all.

Finding yourself in such a painful situation you might end up feeling deeply desperate and hopeless. But one who accepts this uncomfortable truth
about human existence learns to appreciate and value solitude. One who knows how lonely he is and finds others in the same situation ends up acting
in a more kindly manner toward others. And what can be more important than that?
