#+hugo_base_dir: ../
#+author: Amir M. Taati

* TODO Age of Distraction 
:PROPERTIES:
:EXPORT_FILE_NAME: fear-of-the-dark
:END:

It was a cold summer night and I was standing on the road. Standing there in [mere] darkness, all I could see was some little
stars in the sky and branches of trees in the beginning of the road. Staring at darkness, all it did was to stare back at me with
its dark eyes. It was frightening to stand there like that, because you I had a road before me which I had to walk into that
was buried under heavy darkness. Nothing could be seen, nothing could be understood, nothing could be predicted and these
were reasons strong enough to paralyze me. But after a while, probably few minutes or so, of standing in the cold, I eventually
decided to walk into the unknown.

It was astonishing to walk into the darkness, for the moment I walked in everything got brighter. Trees and fear didn't let me see
previously, but now I could see the moon in the sky. It took my eyes few seconds to get used to darkness and after that, under
moonlight, I could actually see things around me. I was surrounded with the exact same [things] as in during the day light.
I had become familiar with everything under sun rays, but now I was rediscovering the same stuff under the moonlight once again.
Standing there under the moonlight, I learned that there was nothing to fear.



